# # -----------------------------------------------------------------------------
# #  Mission IT Applications and Frameworks
# # 
# #  POCs:
# #  Jenna Martins jenna.n.martins@leidos.com
# #  Andrew Stein 
# # 
# #  Authors:
# #  Heidi Harris heidi.l.gray@leidos.com
# #  James Seeman james.seeman@leidos.com
# #  Dorian Mabrey dorian.n.mabrey@leidos.com
# # 
# #  COTS/FOSS SW Dependencies:
# #  Nginx
# #  Flask
# #  Grafana
# #  Prometheus
# #  Kibana

---
- hosts: all
  vars_files: vars.yml
  remote_user: root
  roles:
  - nginx
  - prometheus
  - grafana
  - node_exporter
  - flask

