# # -----------------------------------------------------------------------------
# #  Mission IT Applications and Frameworks
# # 
# #  POCs:
# #  Jenna Martins jenna.n.martins@leidos.com
# # 
# #  Authors:
# #  Heidi Harris heidi.l.gray@leidos.com
# #  James Seeman james.seeman@leidos.com
# #  Dorian Mabrey dorian.n.mabrey@leidos.com
# # 
# #  COTS/FOSS SW Dependencies:
# #  Nginx
# #  Flask
# #  Grafana
# #  Prometheus
# #  Kibana

---
- name: Copy Kibana package
  copy:
   src: kibana-{{ kibana_version }}-{{ kibana_arch }}.rpm
   dest: /tmp/kibana-{{ kibana_version }}-{{ kibana_arch }}.rpm

- name: Install Kibana package
  yum:
    name: /tmp/kibana-{{ kibana_version }}-{{ kibana_arch }}.rpm
    state: present
    disable_gpg_check: yes
  become: true

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana service

- name: add vhost to nginx
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: '^http {'
    line: |
      server {
        listen                   {{ kibana_nginx_port }} ssl;
        server_name              {{ kibana_nginx_server_name }};
        ssl                      on;
        ssl_certificate          /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key      /etc/nginx/ssl/nginx-selfsigned.key;
        ssl_verify_depth         2;
        error_page               497 https://$host:$server_port$request_uri;

        ssl_client_certificate /etc/nginx/ssl/client_certs.crt;
        ssl_verify_client optional;

        location = /auth {
          internal;
          proxy_pass              http://localhost:{{ flask_port }};
          proxy_pass_request_body off;
          proxy_set_header        Content-Length "";
          proxy_set_header        Port $server_port;
          proxy_set_header        X-Forwarded-For $remote_addr;
          proxy_set_header        X-Original-URI $request_uri;
          proxy_set_header        X-SSL-CERT $ssl_client_cert;
          proxy_set_header        X-Client-DN $ssl_client_s_dn;
          proxy_set_header        X-Client-DN-CN $ssl_client_s_dn_cn;
          proxy_set_header        X-Issuer-DN $ssl_client_i_dn;
        }

        location / {
          auth_request /auth;

          proxy_pass               http://localhost:9090;
          if ($ssl_client_verify != SUCCESS) {
            return 403;
          }
        }
      }
    state: present

- name: restart nginx
  service:
    name: nginx
    state: restarted

