#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: localhost.localdomain

rule_files:
  - /etc/prometheus/rules/*.rules

# BEGIN ANSIBLE MANAGED BLOCK
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node
# END ANSIBLE MANAGED BLOCK
