# -----------------------------------------------------------------------------
# #  LEIDOS PROPRIETARY INFORMATION
# # 
# #  Proprietary information owned by LEIDOS that requires protection
# #  from unauthorized disclosure.
# # 
# #  2021 LEIDOS
# # -----------------------------------------------------------------------------
# #  Mission IT Applications and Frameworks
# # 
# #  POCs:
# #  Jenna Martins jenna.n.martins@leidos.com
# #  Andrew Stein andrew.w.stein@leidos.com
# # 
# #  Authors:
# #  Heidi Harris heidi.l.gray@leidos.com
# #  James Seeman james.seeman@leidos.com
# #  Dorian Mabrey dorian.n.mabrey@leidos.com
# # 
# #  COTS/FOSS SW Dependencies:
# #  Nginx
# #  Flask
# #  Grafana
# #  Prometheus
# #  Kibana

---

- name: init kibana service
  systemd:
   state: restarted
   enabled: yes
   daemon_reload: yes
   name: kibana-server

- name: restart firewalld service
  service:
   name: firewalld
   state: restarted

- name: start kibana service
  service:
   name: kibana-server
   state: started

- name: restart kibana service
  service:
   name: kibana-server
   state: restarted
