# # -----------------------------------------------------------------------------
# #  Mission IT Applications and Frameworks
# # 
# #  POCs:
# #  Jenna Martins jenna.n.martins@leidos.com
# #  Andrew Stein 
# # 
# #  Authors:
# #  Heidi Harris heidi.l.gray@leidos.com
# #  James Seeman james.seeman@leidos.com
# #  Dorian Mabrey dorian.n.mabrey@leidos.com
# # 
# #  COTS/FOSS SW Dependencies:
# #  Nginx
# #  Flask
# #  Grafana
# #  Prometheus
# #  Kibana

---
- include: install.yml
  become: yes
  tags:
   - prometheus_install

- include: configure.yml
  become: yes
  tags:
   - prometheus_configure

- name: reload prometheus
  become: true
  systemd:
   daemon_reload: true
   name: prometheus
   state: started
   enabled: true
  tags:
   - prometheus_run
